#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BG0056_00_01Turnstile_Emissive

#include "Basic.hpp"

#include "EndGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BG0056_00_01Turnstile_Emissive.BG0056_00_01Turnstile_Emissive_C
// 0x0000 (0x05F8 - 0x05F8)
class ABG0056_00_01Turnstile_Emissive_C final : public AEndEnvironmentSkeletalMeshActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BG0056_00_01Turnstile_Emissive_C">();
	}
	static class ABG0056_00_01Turnstile_Emissive_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABG0056_00_01Turnstile_Emissive_C>();
	}
};
static_assert(alignof(ABG0056_00_01Turnstile_Emissive_C) == 0x000008, "Wrong alignment on ABG0056_00_01Turnstile_Emissive_C");
static_assert(sizeof(ABG0056_00_01Turnstile_Emissive_C) == 0x0005F8, "Wrong size on ABG0056_00_01Turnstile_Emissive_C");

}

