#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BG1397_00_14CardReaderB_Standard

#include "Basic.hpp"

#include "EndGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BG1397_00_14CardReaderB_Standard.BG1397_00_14CardReaderB_Standard_C
// 0x0000 (0x05F8 - 0x05F8)
class ABG1397_00_14CardReaderB_Standard_C final : public AEndEnvironmentSkeletalMeshActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BG1397_00_14CardReaderB_Standard_C">();
	}
	static class ABG1397_00_14CardReaderB_Standard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABG1397_00_14CardReaderB_Standard_C>();
	}
};
static_assert(alignof(ABG1397_00_14CardReaderB_Standard_C) == 0x000008, "Wrong alignment on ABG1397_00_14CardReaderB_Standard_C");
static_assert(sizeof(ABG1397_00_14CardReaderB_Standard_C) == 0x0005F8, "Wrong size on ABG1397_00_14CardReaderB_Standard_C");

}

