#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BG1333_00_14Signage_Texture

#include "Basic.hpp"

#include "EndGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BG1333_00_14Signage_Texture.BG1333_00_14Signage_Texture_C
// 0x0000 (0x05F8 - 0x05F8)
class ABG1333_00_14Signage_Texture_C final : public AEndEnvironmentSkeletalMeshActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BG1333_00_14Signage_Texture_C">();
	}
	static class ABG1333_00_14Signage_Texture_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABG1333_00_14Signage_Texture_C>();
	}
};
static_assert(alignof(ABG1333_00_14Signage_Texture_C) == 0x000008, "Wrong alignment on ABG1333_00_14Signage_Texture_C");
static_assert(sizeof(ABG1333_00_14Signage_Texture_C) == 0x0005F8, "Wrong size on ABG1333_00_14Signage_Texture_C");

}

