#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: btsc_sbil0_50_boss010

#include "Basic.hpp"

#include "btsc_sbil0_50_boss010_classes.hpp"
#include "btsc_sbil0_50_boss010_parameters.hpp"


namespace SDK
{

// Function btsc_sbil0_50_boss010.btsc_sbil0_50_boss010_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void Abtsc_sbil0_50_boss010_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("btsc_sbil0_50_boss010_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function btsc_sbil0_50_boss010.btsc_sbil0_50_boss010_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void Abtsc_sbil0_50_boss010_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("btsc_sbil0_50_boss010_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function btsc_sbil0_50_boss010.btsc_sbil0_50_boss010_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Abtsc_sbil0_50_boss010_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("btsc_sbil0_50_boss010_C", "ReceiveTick");

	Params::btsc_sbil0_50_boss010_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function btsc_sbil0_50_boss010.btsc_sbil0_50_boss010_C.ChangePhase
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   mphase                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Abtsc_sbil0_50_boss010_C::ChangePhase(int32 mphase)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("btsc_sbil0_50_boss010_C", "ChangePhase");

	Params::btsc_sbil0_50_boss010_C_ChangePhase Parms{};

	Parms.mphase = mphase;

	UObject::ProcessEvent(Func, &Parms);
}


// Function btsc_sbil0_50_boss010.btsc_sbil0_50_boss010_C.ExecuteUbergraph_btsc_sbil0_50_boss010
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Abtsc_sbil0_50_boss010_C::ExecuteUbergraph_btsc_sbil0_50_boss010(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("btsc_sbil0_50_boss010_C", "ExecuteUbergraph_btsc_sbil0_50_boss010");

	Params::btsc_sbil0_50_boss010_C_ExecuteUbergraph_btsc_sbil0_50_boss010 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

