#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: btsc_base

#include "Basic.hpp"

#include "btsc_base_classes.hpp"
#include "btsc_base_parameters.hpp"


namespace SDK
{

// Function btsc_base.btsc_base_C.ExecuteUbergraph_btsc_base
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Abtsc_base_C::ExecuteUbergraph_btsc_base(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("btsc_base_C", "ExecuteUbergraph_btsc_base");

	Params::btsc_base_C_ExecuteUbergraph_btsc_base Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function btsc_base.btsc_base_C.OnIncrementBattleCountPerID
// (Event, Public, BlueprintEvent)
// Parameters:
// class FName                             CauserCharaName                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             TargetCharaName                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEndBattleCountLogType                  Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             ID                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Count                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Abtsc_base_C::OnIncrementBattleCountPerID(class FName CauserCharaName, class FName TargetCharaName, EEndBattleCountLogType Type, class FName ID, int32 Count)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("btsc_base_C", "OnIncrementBattleCountPerID");

	Params::btsc_base_C_OnIncrementBattleCountPerID Parms{};

	Parms.CauserCharaName = CauserCharaName;
	Parms.TargetCharaName = TargetCharaName;
	Parms.Type = Type;
	Parms.ID = ID;
	Parms.Count = Count;

	UObject::ProcessEvent(Func, &Parms);
}


// Function btsc_base.btsc_base_C.OnEndLinkCommand
// (Event, Public, BlueprintEvent)

void Abtsc_base_C::OnEndLinkCommand()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("btsc_base_C", "OnEndLinkCommand");

	UObject::ProcessEvent(Func, nullptr);
}


// Function btsc_base.btsc_base_C.OnBeginLinkCommand
// (Event, Public, BlueprintEvent)

void Abtsc_base_C::OnBeginLinkCommand()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("btsc_base_C", "OnBeginLinkCommand");

	UObject::ProcessEvent(Func, nullptr);
}


// Function btsc_base.btsc_base_C.OnEntryBattleScene
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// class FName                             BattleSceneID                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FEndDataTableBattleScene         dataTableBattleScene                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void Abtsc_base_C::OnEntryBattleScene(const class FName& BattleSceneID, const struct FEndDataTableBattleScene& dataTableBattleScene)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("btsc_base_C", "OnEntryBattleScene");

	Params::btsc_base_C_OnEntryBattleScene Parms{};

	Parms.BattleSceneID = BattleSceneID;
	Parms.dataTableBattleScene = std::move(dataTableBattleScene);

	UObject::ProcessEvent(Func, &Parms);
}


// Function btsc_base.btsc_base_C.plusBattleBegin_SinraB
// (BlueprintCallable, BlueprintEvent)

void Abtsc_base_C::plusBattleBegin_SinraB()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("btsc_base_C", "plusBattleBegin_SinraB");

	UObject::ProcessEvent(Func, nullptr);
}


// Function btsc_base.btsc_base_C.plusBattleBegin_SinraS
// (BlueprintCallable, BlueprintEvent)

void Abtsc_base_C::plusBattleBegin_SinraS()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("btsc_base_C", "plusBattleBegin_SinraS");

	UObject::ProcessEvent(Func, nullptr);
}


// Function btsc_base.btsc_base_C.plusBattleBegin_MonB
// (BlueprintCallable, BlueprintEvent)

void Abtsc_base_C::plusBattleBegin_MonB()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("btsc_base_C", "plusBattleBegin_MonB");

	UObject::ProcessEvent(Func, nullptr);
}


// Function btsc_base.btsc_base_C.plusBattleBegin_MonS
// (BlueprintCallable, BlueprintEvent)

void Abtsc_base_C::plusBattleBegin_MonS()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("btsc_base_C", "plusBattleBegin_MonS");

	UObject::ProcessEvent(Func, nullptr);
}


// Function btsc_base.btsc_base_C.OnDLCSummonUltimateMagicEnd
// (Event, Public, BlueprintEvent)

void Abtsc_base_C::OnDLCSummonUltimateMagicEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("btsc_base_C", "OnDLCSummonUltimateMagicEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function btsc_base.btsc_base_C.OnReadyBattleTalk
// (Event, Public, BlueprintEvent)
// Parameters:
// class FName                             BattleSceneID                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Abtsc_base_C::OnReadyBattleTalk(class FName BattleSceneID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("btsc_base_C", "OnReadyBattleTalk");

	Params::btsc_base_C_OnReadyBattleTalk Parms{};

	Parms.BattleSceneID = BattleSceneID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function btsc_base.btsc_base_C.OnTakeDamage
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// int32                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             CauserCharaName                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             DamagedCharaName                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             AbilityID                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bBind                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bGuard                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bDodge                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FName                             hitBoneName                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bAttributeHit                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FName                             DamageSourceID                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEndBattleAttributeType                 DmgSrcAttributeType                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   justHitRotYaw                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          hitPosition                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bHeal                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Abtsc_base_C::OnTakeDamage(int32 Damage, const class FName& CauserCharaName, const class FName& DamagedCharaName, const class FName& AbilityID, bool bBind, bool bGuard, bool bDodge, const class FName& hitBoneName, bool bAttributeHit, const class FName& DamageSourceID, EEndBattleAttributeType DmgSrcAttributeType, float justHitRotYaw, const struct FVector& hitPosition, bool bHeal)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("btsc_base_C", "OnTakeDamage");

	Params::btsc_base_C_OnTakeDamage Parms{};

	Parms.Damage = Damage;
	Parms.CauserCharaName = CauserCharaName;
	Parms.DamagedCharaName = DamagedCharaName;
	Parms.AbilityID = AbilityID;
	Parms.bBind = bBind;
	Parms.bGuard = bGuard;
	Parms.bDodge = bDodge;
	Parms.hitBoneName = hitBoneName;
	Parms.bAttributeHit = bAttributeHit;
	Parms.DamageSourceID = DamageSourceID;
	Parms.DmgSrcAttributeType = DmgSrcAttributeType;
	Parms.justHitRotYaw = justHitRotYaw;
	Parms.hitPosition = std::move(hitPosition);
	Parms.bHeal = bHeal;

	UObject::ProcessEvent(Func, &Parms);
}


// Function btsc_base.btsc_base_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void Abtsc_base_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("btsc_base_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

