#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Clip_PlaySecondary

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct Clip_PlaySecondary.Clip_PlaySecondary
// 0x0018 (0x0018 - 0x0000)
struct FClip_PlaySecondary final
{
public:
	class FString                                 LevelName_5_3DB47F5D416BDBF5C8A8EFB469694A88;      // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	uint8                                         Priority_21_D7D575C14BD17810F61D389496251A2A;      // 0x0010(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FClip_PlaySecondary) == 0x000008, "Wrong alignment on FClip_PlaySecondary");
static_assert(sizeof(FClip_PlaySecondary) == 0x000018, "Wrong size on FClip_PlaySecondary");
static_assert(offsetof(FClip_PlaySecondary, LevelName_5_3DB47F5D416BDBF5C8A8EFB469694A88) == 0x000000, "Member 'FClip_PlaySecondary::LevelName_5_3DB47F5D416BDBF5C8A8EFB469694A88' has a wrong offset!");
static_assert(offsetof(FClip_PlaySecondary, Priority_21_D7D575C14BD17810F61D389496251A2A) == 0x000010, "Member 'FClip_PlaySecondary::Priority_21_D7D575C14BD17810F61D389496251A2A' has a wrong offset!");

}

