#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Clip_ResetSkippingDeferredRendering

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct Clip_ResetSkippingDeferredRendering.Clip_ResetSkippingDeferredRendering
// 0x0001 (0x0001 - 0x0000)
struct FClip_ResetSkippingDeferredRendering final
{
public:
	uint8                                         Priority_2_28DE96C042FF15DE1F5DE08D4122C429;       // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FClip_ResetSkippingDeferredRendering) == 0x000001, "Wrong alignment on FClip_ResetSkippingDeferredRendering");
static_assert(sizeof(FClip_ResetSkippingDeferredRendering) == 0x000001, "Wrong size on FClip_ResetSkippingDeferredRendering");
static_assert(offsetof(FClip_ResetSkippingDeferredRendering, Priority_2_28DE96C042FF15DE1F5DE08D4122C429) == 0x000000, "Member 'FClip_ResetSkippingDeferredRendering::Priority_2_28DE96C042FF15DE1F5DE08D4122C429' has a wrong offset!");

}

