#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Coliseum_SelectCell

#include "Basic.hpp"

#include "Coliseum_SelectCell_classes.hpp"
#include "Coliseum_SelectCell_parameters.hpp"


namespace SDK
{

// Function Coliseum_SelectCell.Coliseum_SelectCell_C.ExecuteUbergraph_Coliseum_SelectCell
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UColiseum_SelectCell_C::ExecuteUbergraph_Coliseum_SelectCell(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Coliseum_SelectCell_C", "ExecuteUbergraph_Coliseum_SelectCell");

	Params::Coliseum_SelectCell_C_ExecuteUbergraph_Coliseum_SelectCell Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Coliseum_SelectCell.Coliseum_SelectCell_C.BndEvt__MainMenu_Btn_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UColiseum_SelectCell_C::BndEvt__MainMenu_Btn_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Coliseum_SelectCell_C", "BndEvt__MainMenu_Btn_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Coliseum_SelectCell.Coliseum_SelectCell_C.BndEvt__MainMenu_Btn_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UColiseum_SelectCell_C::BndEvt__MainMenu_Btn_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Coliseum_SelectCell_C", "BndEvt__MainMenu_Btn_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Coliseum_SelectCell.Coliseum_SelectCell_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UColiseum_SelectCell_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Coliseum_SelectCell_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

