#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Com_Base_02

#include "Basic.hpp"


namespace SDK::Params
{

// Function Com_Base_02.Com_Base_02_C.ExecuteUbergraph_Com_Base_02
// 0x0004 (0x0004 - 0x0000)
struct Com_Base_02_C_ExecuteUbergraph_Com_Base_02 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Com_Base_02_C_ExecuteUbergraph_Com_Base_02) == 0x000004, "Wrong alignment on Com_Base_02_C_ExecuteUbergraph_Com_Base_02");
static_assert(sizeof(Com_Base_02_C_ExecuteUbergraph_Com_Base_02) == 0x000004, "Wrong size on Com_Base_02_C_ExecuteUbergraph_Com_Base_02");
static_assert(offsetof(Com_Base_02_C_ExecuteUbergraph_Com_Base_02, EntryPoint) == 0x000000, "Member 'Com_Base_02_C_ExecuteUbergraph_Com_Base_02::EntryPoint' has a wrong offset!");

}

