#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EB0003_12_HelicopterTurks_Standard_AI

#include "Basic.hpp"

#include "EB0003_12_HelicopterTurks_Standard_AI_classes.hpp"
#include "EB0003_12_HelicopterTurks_Standard_AI_parameters.hpp"


namespace SDK
{

// Function EB0003_12_HelicopterTurks_Standard_AI.EB0003_12_HelicopterTurks_Standard_AI_C.ExecuteUbergraph_EB0003_12_HelicopterTurks_Standard_AI
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEB0003_12_HelicopterTurks_Standard_AI_C::ExecuteUbergraph_EB0003_12_HelicopterTurks_Standard_AI(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EB0003_12_HelicopterTurks_Standard_AI_C", "ExecuteUbergraph_EB0003_12_HelicopterTurks_Standard_AI");

	Params::EB0003_12_HelicopterTurks_Standard_AI_C_ExecuteUbergraph_EB0003_12_HelicopterTurks_Standard_AI Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EB0003_12_HelicopterTurks_Standard_AI.EB0003_12_HelicopterTurks_Standard_AI_C.ƒWjD
// (BlueprintCallable, BlueprintEvent)

void AEB0003_12_HelicopterTurks_Standard_AI_C::m_WjD()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EB0003_12_HelicopterTurks_Standard_AI_C", "ƒWjD");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EB0003_12_HelicopterTurks_Standard_AI.EB0003_12_HelicopterTurks_Standard_AI_C.OnMetaMessageAboutCharacter
// (Event, Public, BlueprintEvent)
// Parameters:
// class AEndCharacter*                    InChara                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           InMessage                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void AEB0003_12_HelicopterTurks_Standard_AI_C::OnMetaMessageAboutCharacter(class AEndCharacter* InChara, const class FString& InMessage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EB0003_12_HelicopterTurks_Standard_AI_C", "OnMetaMessageAboutCharacter");

	Params::EB0003_12_HelicopterTurks_Standard_AI_C_OnMetaMessageAboutCharacter Parms{};

	Parms.InChara = InChara;
	Parms.InMessage = std::move(InMessage);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EB0003_12_HelicopterTurks_Standard_AI.EB0003_12_HelicopterTurks_Standard_AI_C.¿ü²ÃÈ’‹
// (BlueprintCallable, BlueprintEvent)

void AEB0003_12_HelicopterTurks_Standard_AI_C::m_______()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EB0003_12_HelicopterTurks_Standard_AI_C", "¿ü²ÃÈ’‹");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EB0003_12_HelicopterTurks_Standard_AI.EB0003_12_HelicopterTurks_Standard_AI_C.FinishTimer
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             InName                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEB0003_12_HelicopterTurks_Standard_AI_C::FinishTimer(class FName InName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EB0003_12_HelicopterTurks_Standard_AI_C", "FinishTimer");

	Params::EB0003_12_HelicopterTurks_Standard_AI_C_FinishTimer Parms{};

	Parms.InName = InName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EB0003_12_HelicopterTurks_Standard_AI.EB0003_12_HelicopterTurks_Standard_AI_C.OnMotionMessage
// (Event, Public, BlueprintEvent)
// Parameters:
// class FName                             InMotionName                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             InName                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InIntValue                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InFloatValue                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEB0003_12_HelicopterTurks_Standard_AI_C::OnMotionMessage(class FName InMotionName, class FName InName, int32 InIntValue, float InFloatValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EB0003_12_HelicopterTurks_Standard_AI_C", "OnMotionMessage");

	Params::EB0003_12_HelicopterTurks_Standard_AI_C_OnMotionMessage Parms{};

	Parms.InMotionName = InMotionName;
	Parms.InName = InName;
	Parms.InIntValue = InIntValue;
	Parms.InFloatValue = InFloatValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EB0003_12_HelicopterTurks_Standard_AI.EB0003_12_HelicopterTurks_Standard_AI_C.Õ§üº2B†ê¯¨¹È
// (BlueprintCallable, BlueprintEvent)

void AEB0003_12_HelicopterTurks_Standard_AI_C::m___2B______()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EB0003_12_HelicopterTurks_Standard_AI_C", "Õ§üº2B†ê¯¨¹È");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EB0003_12_HelicopterTurks_Standard_AI.EB0003_12_HelicopterTurks_Standard_AI_C.OnKilled
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AEndCharacter*                    InTarget                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             InName                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    InBind                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEB0003_12_HelicopterTurks_Standard_AI_C::OnKilled(int32 Damage, class AEndCharacter* InTarget, class FName InName, bool InBind)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EB0003_12_HelicopterTurks_Standard_AI_C", "OnKilled");

	Params::EB0003_12_HelicopterTurks_Standard_AI_C_OnKilled Parms{};

	Parms.Damage = Damage;
	Parms.InTarget = InTarget;
	Parms.InName = InName;
	Parms.InBind = InBind;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EB0003_12_HelicopterTurks_Standard_AI.EB0003_12_HelicopterTurks_Standard_AI_C.ƒƒ’„‹
// (BlueprintCallable, BlueprintEvent)

void AEB0003_12_HelicopterTurks_Standard_AI_C::m_____()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EB0003_12_HelicopterTurks_Standard_AI_C", "ƒƒ’„‹");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EB0003_12_HelicopterTurks_Standard_AI.EB0003_12_HelicopterTurks_Standard_AI_C.¨ê¢-.…_nƒƒ
// (BlueprintCallable, BlueprintEvent)

void AEB0003_12_HelicopterTurks_Standard_AI_C::m______n__()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EB0003_12_HelicopterTurks_Standard_AI_C", "¨ê¢-.…_nƒƒ");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EB0003_12_HelicopterTurks_Standard_AI.EB0003_12_HelicopterTurks_Standard_AI_C.Mn…_nƒƒ
// (BlueprintCallable, BlueprintEvent)

void AEB0003_12_HelicopterTurks_Standard_AI_C::m_Mn__n__()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EB0003_12_HelicopterTurks_Standard_AI_C", "Mn…_nƒƒ");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EB0003_12_HelicopterTurks_Standard_AI.EB0003_12_HelicopterTurks_Standard_AI_C.OnFirstUpdate
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EEndAiBattleRole                        InRole                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InStep                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEB0003_12_HelicopterTurks_Standard_AI_C::OnFirstUpdate(EEndAiBattleRole InRole, int32 InStep)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EB0003_12_HelicopterTurks_Standard_AI_C", "OnFirstUpdate");

	Params::EB0003_12_HelicopterTurks_Standard_AI_C_OnFirstUpdate Parms{};

	Parms.InRole = InRole;
	Parms.InStep = InStep;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EB0003_12_HelicopterTurks_Standard_AI.EB0003_12_HelicopterTurks_Standard_AI_C.OnUpdate
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EEndAiBattleRole                        InRole                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InStep                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEB0003_12_HelicopterTurks_Standard_AI_C::OnUpdate(EEndAiBattleRole InRole, int32 InStep, float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EB0003_12_HelicopterTurks_Standard_AI_C", "OnUpdate");

	Params::EB0003_12_HelicopterTurks_Standard_AI_C_OnUpdate Parms{};

	Parms.InRole = InRole;
	Parms.InStep = InStep;
	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EB0003_12_HelicopterTurks_Standard_AI.EB0003_12_HelicopterTurks_Standard_AI_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AEB0003_12_HelicopterTurks_Standard_AI_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EB0003_12_HelicopterTurks_Standard_AI_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

