#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EN0000_01_SecuritySoldier_Senior_AI

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "EN0000_00_SecuritySoldier_Standard_AI_classes.hpp"
#include "EndGame_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass EN0000_01_SecuritySoldier_Senior_AI.EN0000_01_SecuritySoldier_Senior_AI_C
// 0x0008 (0x22D0 - 0x22C8)
class AEN0000_01_SecuritySoldier_Senior_AI_C final : public AEN0000_00_SecuritySoldier_Standard_AI_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_EN0000_01_SecuritySoldier_Senior_AI_C; // 0x22C8(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_EN0000_01_SecuritySoldier_Senior_AI(int32 EntryPoint);
	void DeclareVariable();
	void OnCheckBindAction(class FName ActionName, int32 CheckID, int32 ComboIndex);
	void OnGiveDamage(int32 Damage, class AEndCharacter* InTarget, class FName InName, bool InBind, bool InGuard, bool InJustGuard, bool KeepOver, bool InDodge, bool InCounter, class FName InBoneName, bool InAttributeWeak, class FName InDamageSourceID, bool InSteal, bool heal);
	void OnUpdate(EEndAiBattleRole InRole, int32 InStep, float DeltaTime);
	void OnTakeDamage(int32 Damage, class AEndCharacter* InChara, class FName InName, EEndBattleAbilityCommandType InCommandType, bool InBind, bool InGuard, bool InDodge, class FName InBoneName, bool InAttributeWeak, class FName InDmgSrcID, EEndBattleAttributeType InDmgSrcAttribute, float justHitRotYaw, const struct FVector& hitPosition, bool InHeal, bool InCounter, const struct FEndDataTableBattleDamageSource& dataTableBattleDamageSource, bool useAbilityUCPC);
	void IsEnablePotion();
	void OnATBHardAttackEvent();
	void OnATBLightAttackEvent();
	void OnPrepareProc();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EN0000_01_SecuritySoldier_Senior_AI_C">();
	}
	static class AEN0000_01_SecuritySoldier_Senior_AI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AEN0000_01_SecuritySoldier_Senior_AI_C>();
	}
};
static_assert(alignof(AEN0000_01_SecuritySoldier_Senior_AI_C) == 0x000008, "Wrong alignment on AEN0000_01_SecuritySoldier_Senior_AI_C");
static_assert(sizeof(AEN0000_01_SecuritySoldier_Senior_AI_C) == 0x0022D0, "Wrong size on AEN0000_01_SecuritySoldier_Senior_AI_C");
static_assert(offsetof(AEN0000_01_SecuritySoldier_Senior_AI_C, UberGraphFrame_EN0000_01_SecuritySoldier_Senior_AI_C) == 0x0022C8, "Member 'AEN0000_01_SecuritySoldier_Senior_AI_C::UberGraphFrame_EN0000_01_SecuritySoldier_Senior_AI_C' has a wrong offset!");

}

