#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EN0000_01_SecuritySoldier_Senior

#include "Basic.hpp"

#include "EndGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EN0000_01_SecuritySoldier_Senior.EN0000_01_SecuritySoldier_Senior_C
// 0x0010 (0x22D0 - 0x22C0)
class AEN0000_01_SecuritySoldier_Senior_C final : public AEndCharacter
{
public:
	uint8                                         Pad_22B8[0x8];                                     // 0x22B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UEndRagdollSEComponent*                 EndRagdollSE;                                      // 0x22C0(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EN0000_01_SecuritySoldier_Senior_C">();
	}
	static class AEN0000_01_SecuritySoldier_Senior_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AEN0000_01_SecuritySoldier_Senior_C>();
	}
};
static_assert(alignof(AEN0000_01_SecuritySoldier_Senior_C) == 0x000010, "Wrong alignment on AEN0000_01_SecuritySoldier_Senior_C");
static_assert(sizeof(AEN0000_01_SecuritySoldier_Senior_C) == 0x0022D0, "Wrong size on AEN0000_01_SecuritySoldier_Senior_C");
static_assert(offsetof(AEN0000_01_SecuritySoldier_Senior_C, EndRagdollSE) == 0x0022C0, "Member 'AEN0000_01_SecuritySoldier_Senior_C::EndRagdollSE' has a wrong offset!");

}

