#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EN0000_01_SecuritySoldier_Senior

#include "Basic.hpp"

#include "EN0000_01_SecuritySoldier_Senior_classes.hpp"


namespace SDK
{

// Function EN0000_01_SecuritySoldier_Senior.EN0000_01_SecuritySoldier_Senior_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AEN0000_01_SecuritySoldier_Senior_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN0000_01_SecuritySoldier_Senior_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

