#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EN9000_00_Feeler_Standard_AI

#include "Basic.hpp"

#include "EN9000_00_Feeler_Standard_AI_classes.hpp"
#include "EN9000_00_Feeler_Standard_AI_parameters.hpp"


namespace SDK
{

// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.ExecuteUbergraph_EN9000_00_Feeler_Standard_AI
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN9000_00_Feeler_Standard_AI_C::ExecuteUbergraph_EN9000_00_Feeler_Standard_AI(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "ExecuteUbergraph_EN9000_00_Feeler_Standard_AI");

	Params::EN9000_00_Feeler_Standard_AI_C_ExecuteUbergraph_EN9000_00_Feeler_Standard_AI Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnMotionMessage
// (Event, Public, BlueprintEvent)
// Parameters:
// class FName                             InMotionName                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             InName                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InIntValue                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InFloatValue                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN9000_00_Feeler_Standard_AI_C::OnMotionMessage(class FName InMotionName, class FName InName, int32 InIntValue, float InFloatValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnMotionMessage");

	Params::EN9000_00_Feeler_Standard_AI_C_OnMotionMessage Parms{};

	Parms.InMotionName = InMotionName;
	Parms.InName = InName;
	Parms.InIntValue = InIntValue;
	Parms.InFloatValue = InFloatValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AEN9000_00_Feeler_Standard_AI_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN9000_00_Feeler_Standard_AI_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "ReceiveTick");

	Params::EN9000_00_Feeler_Standard_AI_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.RetryReinforce
// (BlueprintCallable, BlueprintEvent)

void AEN9000_00_Feeler_Standard_AI_C::RetryReinforce()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "RetryReinforce");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnDestroyDamageSource
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// class FName                             DamageSourceID                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Location                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN9000_00_Feeler_Standard_AI_C::OnDestroyDamageSource(const class FName& DamageSourceID, const struct FVector& Location)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnDestroyDamageSource");

	Params::EN9000_00_Feeler_Standard_AI_C_OnDestroyDamageSource Parms{};

	Parms.DamageSourceID = DamageSourceID;
	Parms.Location = std::move(Location);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.SuspendGraviton
// (BlueprintCallable, BlueprintEvent)

void AEN9000_00_Feeler_Standard_AI_C::SuspendGraviton()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "SuspendGraviton");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnUpdate
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EEndAiBattleRole                        InRole                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InStep                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN9000_00_Feeler_Standard_AI_C::OnUpdate(EEndAiBattleRole InRole, int32 InStep, float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnUpdate");

	Params::EN9000_00_Feeler_Standard_AI_C_OnUpdate Parms{};

	Parms.InRole = InRole;
	Parms.InStep = InStep;
	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnKilled
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AEndCharacter*                    InTarget                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             InName                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    InBind                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEN9000_00_Feeler_Standard_AI_C::OnKilled(int32 Damage, class AEndCharacter* InTarget, class FName InName, bool InBind)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnKilled");

	Params::EN9000_00_Feeler_Standard_AI_C_OnKilled Parms{};

	Parms.Damage = Damage;
	Parms.InTarget = InTarget;
	Parms.InName = InName;
	Parms.InBind = InBind;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.VortexSupplement
// (BlueprintCallable, BlueprintEvent)

void AEN9000_00_Feeler_Standard_AI_C::VortexSupplement()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "VortexSupplement");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnBurstEnd
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    instant                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEN9000_00_Feeler_Standard_AI_C::OnBurstEnd(bool instant)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnBurstEnd");

	Params::EN9000_00_Feeler_Standard_AI_C_OnBurstEnd Parms{};

	Parms.instant = instant;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnBurstBegin
// (Event, Public, BlueprintEvent)

void AEN9000_00_Feeler_Standard_AI_C::OnBurstBegin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnBurstBegin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnEntryBattleScene
// (Event, Public, BlueprintEvent)

void AEN9000_00_Feeler_Standard_AI_C::OnEntryBattleScene()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnEntryBattleScene");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OrderStandByVortex
// (BlueprintCallable, BlueprintEvent)

void AEN9000_00_Feeler_Standard_AI_C::OrderStandByVortex()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OrderStandByVortex");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnInterceptAbility
// (Event, Public, BlueprintEvent)
// Parameters:
// class FName                             InName                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN9000_00_Feeler_Standard_AI_C::OnInterceptAbility(class FName InName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnInterceptAbility");

	Params::EN9000_00_Feeler_Standard_AI_C_OnInterceptAbility Parms{};

	Parms.InName = InName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnMetaEventTakeDamage
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AEndCharacter*                    InSender                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AEndCharacter*                    InReceiver                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             InName                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    InBind                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    InGuard                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    InDodge                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FName                             InBoneName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    InAttributeWeak                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    InHeal                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEN9000_00_Feeler_Standard_AI_C::OnMetaEventTakeDamage(int32 Damage, class AEndCharacter* InSender, class AEndCharacter* InReceiver, class FName InName, bool InBind, bool InGuard, bool InDodge, class FName InBoneName, bool InAttributeWeak, bool InHeal)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnMetaEventTakeDamage");

	Params::EN9000_00_Feeler_Standard_AI_C_OnMetaEventTakeDamage Parms{};

	Parms.Damage = Damage;
	Parms.InSender = InSender;
	Parms.InReceiver = InReceiver;
	Parms.InName = InName;
	Parms.InBind = InBind;
	Parms.InGuard = InGuard;
	Parms.InDodge = InDodge;
	Parms.InBoneName = InBoneName;
	Parms.InAttributeWeak = InAttributeWeak;
	Parms.InHeal = InHeal;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnEventRemoveWeakCondition
// (Event, Public, BlueprintEvent)
// Parameters:
// EEndBattleWeakConditionType             ConditionType                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN9000_00_Feeler_Standard_AI_C::OnEventRemoveWeakCondition(EEndBattleWeakConditionType ConditionType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnEventRemoveWeakCondition");

	Params::EN9000_00_Feeler_Standard_AI_C_OnEventRemoveWeakCondition Parms{};

	Parms.ConditionType = ConditionType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnEventAddWeakCondition
// (Event, Public, BlueprintEvent)
// Parameters:
// EEndBattleWeakConditionType             ConditionType                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN9000_00_Feeler_Standard_AI_C::OnEventAddWeakCondition(EEndBattleWeakConditionType ConditionType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnEventAddWeakCondition");

	Params::EN9000_00_Feeler_Standard_AI_C_OnEventAddWeakCondition Parms{};

	Parms.ConditionType = ConditionType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.ClearRagePow
// (BlueprintCallable, BlueprintEvent)

void AEN9000_00_Feeler_Standard_AI_C::ClearRagePow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "ClearRagePow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnTakeDamageOnce
// (Event, Public, BlueprintEvent)
// Parameters:
// class AEndCharacter*                    InCauserChara                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             InAbilityID                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    InAttributeWeak                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// EEndBattleAbilityCommandType            AbilityCommandType                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN9000_00_Feeler_Standard_AI_C::OnTakeDamageOnce(class AEndCharacter* InCauserChara, class FName InAbilityID, bool InAttributeWeak, EEndBattleAbilityCommandType AbilityCommandType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnTakeDamageOnce");

	Params::EN9000_00_Feeler_Standard_AI_C_OnTakeDamageOnce Parms{};

	Parms.InCauserChara = InCauserChara;
	Parms.InAbilityID = InAbilityID;
	Parms.InAttributeWeak = InAttributeWeak;
	Parms.AbilityCommandType = AbilityCommandType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.NextOnUpdate
// (BlueprintCallable, BlueprintEvent)

void AEN9000_00_Feeler_Standard_AI_C::NextOnUpdate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "NextOnUpdate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnMotionStateMessageBegin
// (Event, Public, BlueprintEvent)
// Parameters:
// class FName                             InMotionName                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             InName                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InIntValue                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InFloatValue                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InTotalDuration                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN9000_00_Feeler_Standard_AI_C::OnMotionStateMessageBegin(class FName InMotionName, class FName InName, int32 InIntValue, float InFloatValue, float InTotalDuration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnMotionStateMessageBegin");

	Params::EN9000_00_Feeler_Standard_AI_C_OnMotionStateMessageBegin Parms{};

	Parms.InMotionName = InMotionName;
	Parms.InName = InName;
	Parms.InIntValue = InIntValue;
	Parms.InFloatValue = InFloatValue;
	Parms.InTotalDuration = InTotalDuration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnSuspendAbility
// (Event, Public, BlueprintEvent)
// Parameters:
// class FName                             InName                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEndAiAbilitySuspendFactor              InFactor                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEndAiAbilitySuspendTiming              InTiming                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN9000_00_Feeler_Standard_AI_C::OnSuspendAbility(class FName InName, EEndAiAbilitySuspendFactor InFactor, EEndAiAbilitySuspendTiming InTiming)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnSuspendAbility");

	Params::EN9000_00_Feeler_Standard_AI_C_OnSuspendAbility Parms{};

	Parms.InName = InName;
	Parms.InFactor = InFactor;
	Parms.InTiming = InTiming;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.DoAtkSting01
// (BlueprintCallable, BlueprintEvent)

void AEN9000_00_Feeler_Standard_AI_C::DoAtkSting01()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "DoAtkSting01");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.FinishVortex
// (BlueprintCallable, BlueprintEvent)

void AEN9000_00_Feeler_Standard_AI_C::FinishVortex()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "FinishVortex");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.RushMode_AtkCling
// (BlueprintCallable, BlueprintEvent)

void AEN9000_00_Feeler_Standard_AI_C::RushMode_AtkCling()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "RushMode_AtkCling");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnFinishDispacher
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             InName                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN9000_00_Feeler_Standard_AI_C::OnFinishDispacher(class FName InName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnFinishDispacher");

	Params::EN9000_00_Feeler_Standard_AI_C_OnFinishDispacher Parms{};

	Parms.InName = InName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.ReadyToBattleFinish
// (BlueprintCallable, BlueprintEvent)

void AEN9000_00_Feeler_Standard_AI_C::ReadyToBattleFinish()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "ReadyToBattleFinish");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnCompleteAbility
// (Event, Public, BlueprintEvent)
// Parameters:
// class FName                             InName                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN9000_00_Feeler_Standard_AI_C::OnCompleteAbility(class FName InName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnCompleteAbility");

	Params::EN9000_00_Feeler_Standard_AI_C_OnCompleteAbility Parms{};

	Parms.InName = InName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnGiveDamage
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AEndCharacter*                    InTarget                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             InName                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    InBind                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    InGuard                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    InJustGuard                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    KeepOver                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    InDodge                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    InCounter                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FName                             InBoneName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    InAttributeWeak                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FName                             InDamageSourceID                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    InSteal                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    heal                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEN9000_00_Feeler_Standard_AI_C::OnGiveDamage(int32 Damage, class AEndCharacter* InTarget, class FName InName, bool InBind, bool InGuard, bool InJustGuard, bool KeepOver, bool InDodge, bool InCounter, class FName InBoneName, bool InAttributeWeak, class FName InDamageSourceID, bool InSteal, bool heal)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnGiveDamage");

	Params::EN9000_00_Feeler_Standard_AI_C_OnGiveDamage Parms{};

	Parms.Damage = Damage;
	Parms.InTarget = InTarget;
	Parms.InName = InName;
	Parms.InBind = InBind;
	Parms.InGuard = InGuard;
	Parms.InJustGuard = InJustGuard;
	Parms.KeepOver = KeepOver;
	Parms.InDodge = InDodge;
	Parms.InCounter = InCounter;
	Parms.InBoneName = InBoneName;
	Parms.InAttributeWeak = InAttributeWeak;
	Parms.InDamageSourceID = InDamageSourceID;
	Parms.InSteal = InSteal;
	Parms.heal = heal;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnMetaMessage
// (Event, Public, BlueprintEvent)
// Parameters:
// class FString                           InMessage                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void AEN9000_00_Feeler_Standard_AI_C::OnMetaMessage(const class FString& InMessage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnMetaMessage");

	Params::EN9000_00_Feeler_Standard_AI_C_OnMetaMessage Parms{};

	Parms.InMessage = std::move(InMessage);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnMetaMessageAboutCharacter
// (Event, Public, BlueprintEvent)
// Parameters:
// class AEndCharacter*                    InChara                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           InMessage                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void AEN9000_00_Feeler_Standard_AI_C::OnMetaMessageAboutCharacter(class AEndCharacter* InChara, const class FString& InMessage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnMetaMessageAboutCharacter");

	Params::EN9000_00_Feeler_Standard_AI_C_OnMetaMessageAboutCharacter Parms{};

	Parms.InChara = InChara;
	Parms.InMessage = std::move(InMessage);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnSyncActionChange
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// class FName                             syncActionID                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             ChangeID                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             DetachDamageSourceID                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN9000_00_Feeler_Standard_AI_C::OnSyncActionChange(const class FName& syncActionID, const class FName& ChangeID, const class FName& DetachDamageSourceID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnSyncActionChange");

	Params::EN9000_00_Feeler_Standard_AI_C_OnSyncActionChange Parms{};

	Parms.syncActionID = syncActionID;
	Parms.ChangeID = ChangeID;
	Parms.DetachDamageSourceID = DetachDamageSourceID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.LoopBreak
// (BlueprintCallable, BlueprintEvent)

void AEN9000_00_Feeler_Standard_AI_C::LoopBreak()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "LoopBreak");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnDead
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    AtBurst                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEN9000_00_Feeler_Standard_AI_C::OnDead(bool AtBurst)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnDead");

	Params::EN9000_00_Feeler_Standard_AI_C_OnDead Parms{};

	Parms.AtBurst = AtBurst;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnFirstUpdate
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EEndAiBattleRole                        InRole                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InStep                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN9000_00_Feeler_Standard_AI_C::OnFirstUpdate(EEndAiBattleRole InRole, int32 InStep)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnFirstUpdate");

	Params::EN9000_00_Feeler_Standard_AI_C_OnFirstUpdate Parms{};

	Parms.InRole = InRole;
	Parms.InStep = InStep;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.OnChangeStep
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InStep                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEN9000_00_Feeler_Standard_AI_C::OnChangeStep(int32 InStep)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "OnChangeStep");

	Params::EN9000_00_Feeler_Standard_AI_C_OnChangeStep Parms{};

	Parms.InStep = InStep;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EN9000_00_Feeler_Standard_AI.EN9000_00_Feeler_Standard_AI_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AEN9000_00_Feeler_Standard_AI_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EN9000_00_Feeler_Standard_AI_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

