#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EnemyWeakPoint

#include "Basic.hpp"

#include "EndGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass EnemyWeakPoint.EnemyWeakPoint_C
// 0x0010 (0x0370 - 0x0360)
class UEnemyWeakPoint_C final : public UEndUserWidget
{
public:
	class UWidgetAnimation*                       In;                                                // 0x0360(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEndImage*                              Icon_00;                                           // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EnemyWeakPoint_C">();
	}
	static class UEnemyWeakPoint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEnemyWeakPoint_C>();
	}
};
static_assert(alignof(UEnemyWeakPoint_C) == 0x000008, "Wrong alignment on UEnemyWeakPoint_C");
static_assert(sizeof(UEnemyWeakPoint_C) == 0x000370, "Wrong size on UEnemyWeakPoint_C");
static_assert(offsetof(UEnemyWeakPoint_C, In) == 0x000360, "Member 'UEnemyWeakPoint_C::In' has a wrong offset!");
static_assert(offsetof(UEnemyWeakPoint_C, Icon_00) == 0x000368, "Member 'UEnemyWeakPoint_C::Icon_00' has a wrong offset!");

}

