#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FA0052_00_Dummy_Standard_Animation

#include "Basic.hpp"

#include "FA0052_00_Dummy_Standard_Animation_classes.hpp"
#include "FA0052_00_Dummy_Standard_Animation_parameters.hpp"


namespace SDK
{

// Function FA0052_00_Dummy_Standard_Animation.FA0052_00_Dummy_Standard_Animation_C.ExecuteUbergraph_FA0052_00_Dummy_Standard_Animation
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFA0052_00_Dummy_Standard_Animation_C::ExecuteUbergraph_FA0052_00_Dummy_Standard_Animation(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FA0052_00_Dummy_Standard_Animation_C", "ExecuteUbergraph_FA0052_00_Dummy_Standard_Animation");

	Params::FA0052_00_Dummy_Standard_Animation_C_ExecuteUbergraph_FA0052_00_Dummy_Standard_Animation Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

