#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FieldQuestIcon

#include "Basic.hpp"

#include "EndGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FieldQuestIcon.FieldQuestIcon_C
// 0x0010 (0x0370 - 0x0360)
class UFieldQuestIcon_C final : public UEndUserWidget
{
public:
	class UEndImage*                              Img_Line;                                          // 0x0360(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEndImageSet*                           Ims_QuestIcon;                                     // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FieldQuestIcon_C">();
	}
	static class UFieldQuestIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFieldQuestIcon_C>();
	}
};
static_assert(alignof(UFieldQuestIcon_C) == 0x000008, "Wrong alignment on UFieldQuestIcon_C");
static_assert(sizeof(UFieldQuestIcon_C) == 0x000370, "Wrong size on UFieldQuestIcon_C");
static_assert(offsetof(UFieldQuestIcon_C, Img_Line) == 0x000360, "Member 'UFieldQuestIcon_C::Img_Line' has a wrong offset!");
static_assert(offsetof(UFieldQuestIcon_C, Ims_QuestIcon) == 0x000368, "Member 'UFieldQuestIcon_C::Ims_QuestIcon' has a wrong offset!");

}

