#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenu_EquipCommandCell

#include "Basic.hpp"

#include "EndGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass MainMenu_EquipCommandCell.MainMenu_EquipCommandCell_C
// 0x0000 (0x0360 - 0x0360)
class UMainMenu_EquipCommandCell_C final : public UEndUserWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MainMenu_EquipCommandCell_C">();
	}
	static class UMainMenu_EquipCommandCell_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMainMenu_EquipCommandCell_C>();
	}
};
static_assert(alignof(UMainMenu_EquipCommandCell_C) == 0x000008, "Wrong alignment on UMainMenu_EquipCommandCell_C");
static_assert(sizeof(UMainMenu_EquipCommandCell_C) == 0x000360, "Wrong size on UMainMenu_EquipCommandCell_C");

}

