#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenu_BattleSettingTop2

#include "Basic.hpp"

#include "MainMenu_BattleSettingTop2_classes.hpp"
#include "MainMenu_BattleSettingTop2_parameters.hpp"


namespace SDK
{

// Function MainMenu_BattleSettingTop2.MainMenu_BattleSettingTop2_C.ExecuteUbergraph_MainMenu_BattleSettingTop2
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainMenu_BattleSettingTop2_C::ExecuteUbergraph_MainMenu_BattleSettingTop2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_BattleSettingTop2_C", "ExecuteUbergraph_MainMenu_BattleSettingTop2");

	Params::MainMenu_BattleSettingTop2_C_ExecuteUbergraph_MainMenu_BattleSettingTop2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenu_BattleSettingTop2.MainMenu_BattleSettingTop2_C.Command_Select
// (BlueprintCallable, BlueprintEvent)

void UMainMenu_BattleSettingTop2_C::Command_Select()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_BattleSettingTop2_C", "Command_Select");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu_BattleSettingTop2.MainMenu_BattleSettingTop2_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UMainMenu_BattleSettingTop2_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_BattleSettingTop2_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu_BattleSettingTop2.MainMenu_BattleSettingTop2_C.Limit_Select
// (BlueprintCallable, BlueprintEvent)

void UMainMenu_BattleSettingTop2_C::Limit_Select()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_BattleSettingTop2_C", "Limit_Select");

	UObject::ProcessEvent(Func, nullptr);
}

}

