#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenu_Equip_Block

#include "Basic.hpp"

#include "MainMenu_Equip_Block_classes.hpp"
#include "MainMenu_Equip_Block_parameters.hpp"


namespace SDK
{

// Function MainMenu_Equip_Block.MainMenu_Equip_Block_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UMainMenu_Equip_Block_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_Equip_Block_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu_Equip_Block.MainMenu_Equip_Block_C.ExecuteUbergraph_MainMenu_Equip_Block
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainMenu_Equip_Block_C::ExecuteUbergraph_MainMenu_Equip_Block(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_Equip_Block_C", "ExecuteUbergraph_MainMenu_Equip_Block");

	Params::MainMenu_Equip_Block_C_ExecuteUbergraph_MainMenu_Equip_Block Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenu_Equip_Block.MainMenu_Equip_Block_C.UpdateEquipStatus
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Attack                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Defense                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   MagicAttack                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   MagicDefense                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainMenu_Equip_Block_C::UpdateEquipStatus(int32 Attack, int32 Defense, int32 MagicAttack, int32 MagicDefense)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_Equip_Block_C", "UpdateEquipStatus");

	Params::MainMenu_Equip_Block_C_UpdateEquipStatus Parms{};

	Parms.Attack = Attack;
	Parms.Defense = Defense;
	Parms.MagicAttack = MagicAttack;
	Parms.MagicDefense = MagicDefense;

	UObject::ProcessEvent(Func, &Parms);
}

}

