#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenu_EnemyReport_ListItemBg

#include "Basic.hpp"

#include "EndGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass MainMenu_EnemyReport_ListItemBg.MainMenu_EnemyReport_ListItemBg_C
// 0x0008 (0x0398 - 0x0390)
class UMainMenu_EnemyReport_ListItemBg_C final : public UEndMainItemSelectBtnText
{
public:
	class UEndImage*                              Base;                                              // 0x0390(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MainMenu_EnemyReport_ListItemBg_C">();
	}
	static class UMainMenu_EnemyReport_ListItemBg_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMainMenu_EnemyReport_ListItemBg_C>();
	}
};
static_assert(alignof(UMainMenu_EnemyReport_ListItemBg_C) == 0x000008, "Wrong alignment on UMainMenu_EnemyReport_ListItemBg_C");
static_assert(sizeof(UMainMenu_EnemyReport_ListItemBg_C) == 0x000398, "Wrong size on UMainMenu_EnemyReport_ListItemBg_C");
static_assert(offsetof(UMainMenu_EnemyReport_ListItemBg_C, Base) == 0x000390, "Member 'UMainMenu_EnemyReport_ListItemBg_C::Base' has a wrong offset!");

}

