#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenu_WeaponUpgrade_StarIcon

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "EndGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass MainMenu_WeaponUpgrade_StarIcon.MainMenu_WeaponUpgrade_StarIcon_C
// 0x0010 (0x0370 - 0x0360)
class UMainMenu_WeaponUpgrade_StarIcon_C final : public UEndUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0360(0x0008)(Transient, DuplicateTransient)
	class UEndImageSet*                           Icon_Star;                                         // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_MainMenu_WeaponUpgrade_StarIcon(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MainMenu_WeaponUpgrade_StarIcon_C">();
	}
	static class UMainMenu_WeaponUpgrade_StarIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMainMenu_WeaponUpgrade_StarIcon_C>();
	}
};
static_assert(alignof(UMainMenu_WeaponUpgrade_StarIcon_C) == 0x000008, "Wrong alignment on UMainMenu_WeaponUpgrade_StarIcon_C");
static_assert(sizeof(UMainMenu_WeaponUpgrade_StarIcon_C) == 0x000370, "Wrong size on UMainMenu_WeaponUpgrade_StarIcon_C");
static_assert(offsetof(UMainMenu_WeaponUpgrade_StarIcon_C, UberGraphFrame) == 0x000360, "Member 'UMainMenu_WeaponUpgrade_StarIcon_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UMainMenu_WeaponUpgrade_StarIcon_C, Icon_Star) == 0x000368, "Member 'UMainMenu_WeaponUpgrade_StarIcon_C::Icon_Star' has a wrong offset!");

}

