#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenu_MateriaEquipTop

#include "Basic.hpp"

#include "MainMenu_MateriaEquipTop_classes.hpp"
#include "MainMenu_MateriaEquipTop_parameters.hpp"


namespace SDK
{

// Function MainMenu_MateriaEquipTop.MainMenu_MateriaEquipTop_C.ExecuteUbergraph_MainMenu_MateriaEquipTop
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainMenu_MateriaEquipTop_C::ExecuteUbergraph_MainMenu_MateriaEquipTop(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_MateriaEquipTop_C", "ExecuteUbergraph_MainMenu_MateriaEquipTop");

	Params::MainMenu_MateriaEquipTop_C_ExecuteUbergraph_MainMenu_MateriaEquipTop Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenu_MateriaEquipTop.MainMenu_MateriaEquipTop_C.UpdateStatusPanelWithMateria
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EPlayerType                             PlayerType                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEquipmentCategoryMain                  EquipType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   SlotIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OrigMateriaIndex                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   TargetMateriaIndex                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainMenu_MateriaEquipTop_C::UpdateStatusPanelWithMateria(EPlayerType PlayerType, EEquipmentCategoryMain EquipType, int32 SlotIndex, int32 OrigMateriaIndex, int32 TargetMateriaIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_MateriaEquipTop_C", "UpdateStatusPanelWithMateria");

	Params::MainMenu_MateriaEquipTop_C_UpdateStatusPanelWithMateria Parms{};

	Parms.PlayerType = PlayerType;
	Parms.EquipType = EquipType;
	Parms.SlotIndex = SlotIndex;
	Parms.OrigMateriaIndex = OrigMateriaIndex;
	Parms.TargetMateriaIndex = TargetMateriaIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenu_MateriaEquipTop.MainMenu_MateriaEquipTop_C.UpdateStatusPanelWithEquipment
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EPlayerType                             PlayerType                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEquipmentCategoryMain                  EquipType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             EquipID                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   EquipIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainMenu_MateriaEquipTop_C::UpdateStatusPanelWithEquipment(EPlayerType PlayerType, EEquipmentCategoryMain EquipType, const class FName& EquipID, int32 EquipIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_MateriaEquipTop_C", "UpdateStatusPanelWithEquipment");

	Params::MainMenu_MateriaEquipTop_C_UpdateStatusPanelWithEquipment Parms{};

	Parms.PlayerType = PlayerType;
	Parms.EquipType = EquipType;
	Parms.EquipID = EquipID;
	Parms.EquipIndex = EquipIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenu_MateriaEquipTop.MainMenu_MateriaEquipTop_C.UpdateStatusPanel
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EPlayerType                             PlayerType                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainMenu_MateriaEquipTop_C::UpdateStatusPanel(EPlayerType PlayerType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_MateriaEquipTop_C", "UpdateStatusPanel");

	Params::MainMenu_MateriaEquipTop_C_UpdateStatusPanel Parms{};

	Parms.PlayerType = PlayerType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenu_MateriaEquipTop.MainMenu_MateriaEquipTop_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UMainMenu_MateriaEquipTop_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_MateriaEquipTop_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

