#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Map_LeftMenuCellLight

#include "Basic.hpp"

#include "Map_LeftMenuCellLight_classes.hpp"
#include "Map_LeftMenuCellLight_parameters.hpp"


namespace SDK
{

// Function Map_LeftMenuCellLight.Map_LeftMenuCellLight_C.ExecuteUbergraph_Map_LeftMenuCellLight
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMap_LeftMenuCellLight_C::ExecuteUbergraph_Map_LeftMenuCellLight(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Map_LeftMenuCellLight_C", "ExecuteUbergraph_Map_LeftMenuCellLight");

	Params::Map_LeftMenuCellLight_C_ExecuteUbergraph_Map_LeftMenuCellLight Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Map_LeftMenuCellLight.Map_LeftMenuCellLight_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UMap_LeftMenuCellLight_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Map_LeftMenuCellLight_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

