#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PC0004_00_RedXIII_Field_AI

#include "Basic.hpp"

#include "PC_Field_Base_AI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PC0004_00_RedXIII_Field_AI.PC0004_00_RedXIII_Field_AI_C
// 0x0000 (0x5758 - 0x5758)
class APC0004_00_RedXIII_Field_AI_C final : public APC_Field_Base_AI_C
{
public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PC0004_00_RedXIII_Field_AI_C">();
	}
	static class APC0004_00_RedXIII_Field_AI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APC0004_00_RedXIII_Field_AI_C>();
	}
};
static_assert(alignof(APC0004_00_RedXIII_Field_AI_C) == 0x000008, "Wrong alignment on APC0004_00_RedXIII_Field_AI_C");
static_assert(sizeof(APC0004_00_RedXIII_Field_AI_C) == 0x005758, "Wrong size on APC0004_00_RedXIII_Field_AI_C");

}

