#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PC0001_00_Barret_Standard_AI

#include "Basic.hpp"

#include "PC0001_00_Barret_Standard_AI_classes.hpp"
#include "PC0001_00_Barret_Standard_AI_parameters.hpp"


namespace SDK
{

// Function PC0001_00_Barret_Standard_AI.PC0001_00_Barret_Standard_AI_C.ExecuteUbergraph_PC0001_00_Barret_Standard_AI
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC0001_00_Barret_Standard_AI_C::ExecuteUbergraph_PC0001_00_Barret_Standard_AI(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC0001_00_Barret_Standard_AI_C", "ExecuteUbergraph_PC0001_00_Barret_Standard_AI");

	Params::PC0001_00_Barret_Standard_AI_C_ExecuteUbergraph_PC0001_00_Barret_Standard_AI Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC0001_00_Barret_Standard_AI.PC0001_00_Barret_Standard_AI_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void APC0001_00_Barret_Standard_AI_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC0001_00_Barret_Standard_AI_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC0001_00_Barret_Standard_AI.PC0001_00_Barret_Standard_AI_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void APC0001_00_Barret_Standard_AI_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC0001_00_Barret_Standard_AI_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

