#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PC0099_03_Toad_Tifa_AI

#include "Basic.hpp"

#include "PC0099_03_Toad_Tifa_AI_classes.hpp"
#include "PC0099_03_Toad_Tifa_AI_parameters.hpp"


namespace SDK
{

// Function PC0099_03_Toad_Tifa_AI.PC0099_03_Toad_Tifa_AI_C.ExecuteUbergraph_PC0099_03_Toad_Tifa_AI
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC0099_03_Toad_Tifa_AI_C::ExecuteUbergraph_PC0099_03_Toad_Tifa_AI(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC0099_03_Toad_Tifa_AI_C", "ExecuteUbergraph_PC0099_03_Toad_Tifa_AI");

	Params::PC0099_03_Toad_Tifa_AI_C_ExecuteUbergraph_PC0099_03_Toad_Tifa_AI Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC0099_03_Toad_Tifa_AI.PC0099_03_Toad_Tifa_AI_C.OnPossess
// (Event, Public, BlueprintEvent)
// Parameters:
// class APawn*                            PossessedPawn                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC0099_03_Toad_Tifa_AI_C::OnPossess(class APawn* PossessedPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC0099_03_Toad_Tifa_AI_C", "OnPossess");

	Params::PC0099_03_Toad_Tifa_AI_C_OnPossess Parms{};

	Parms.PossessedPawn = PossessedPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC0099_03_Toad_Tifa_AI.PC0099_03_Toad_Tifa_AI_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void APC0099_03_Toad_Tifa_AI_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC0099_03_Toad_Tifa_AI_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC0099_03_Toad_Tifa_AI.PC0099_03_Toad_Tifa_AI_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void APC0099_03_Toad_Tifa_AI_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC0099_03_Toad_Tifa_AI_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

