#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PC_Field_Base_AI

#include "Basic.hpp"


namespace SDK::Params
{

// Function PC_Field_Base_AI.PC_Field_Base_AI_C.ExecuteUbergraph_PC_Field_Base_AI
// 0x0008 (0x0008 - 0x0000)
struct PC_Field_Base_AI_C_ExecuteUbergraph_PC_Field_Base_AI final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_RunBehaviorTree_ReturnValue;              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(PC_Field_Base_AI_C_ExecuteUbergraph_PC_Field_Base_AI) == 0x000004, "Wrong alignment on PC_Field_Base_AI_C_ExecuteUbergraph_PC_Field_Base_AI");
static_assert(sizeof(PC_Field_Base_AI_C_ExecuteUbergraph_PC_Field_Base_AI) == 0x000008, "Wrong size on PC_Field_Base_AI_C_ExecuteUbergraph_PC_Field_Base_AI");
static_assert(offsetof(PC_Field_Base_AI_C_ExecuteUbergraph_PC_Field_Base_AI, EntryPoint) == 0x000000, "Member 'PC_Field_Base_AI_C_ExecuteUbergraph_PC_Field_Base_AI::EntryPoint' has a wrong offset!");
static_assert(offsetof(PC_Field_Base_AI_C_ExecuteUbergraph_PC_Field_Base_AI, CallFunc_RunBehaviorTree_ReturnValue) == 0x000004, "Member 'PC_Field_Base_AI_C_ExecuteUbergraph_PC_Field_Base_AI::CallFunc_RunBehaviorTree_ReturnValue' has a wrong offset!");

}

