#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PC_Field_Base_AI

#include "Basic.hpp"

#include "PC_Field_Base_AI_classes.hpp"
#include "PC_Field_Base_AI_parameters.hpp"


namespace SDK
{

// Function PC_Field_Base_AI.PC_Field_Base_AI_C.ExecuteUbergraph_PC_Field_Base_AI
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Field_Base_AI_C::ExecuteUbergraph_PC_Field_Base_AI(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Field_Base_AI_C", "ExecuteUbergraph_PC_Field_Base_AI");

	Params::PC_Field_Base_AI_C_ExecuteUbergraph_PC_Field_Base_AI Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Field_Base_AI.PC_Field_Base_AI_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void APC_Field_Base_AI_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Field_Base_AI_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC_Field_Base_AI.PC_Field_Base_AI_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void APC_Field_Base_AI_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Field_Base_AI_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

