#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Resident_Asset

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Resident_Asset.Resident_Asset_C
// 0x0008 (0x0388 - 0x0380)
class AResident_Asset_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0380(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Resident_Asset(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Resident_Asset_C">();
	}
	static class AResident_Asset_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AResident_Asset_C>();
	}
};
static_assert(alignof(AResident_Asset_C) == 0x000008, "Wrong alignment on AResident_Asset_C");
static_assert(sizeof(AResident_Asset_C) == 0x000388, "Wrong size on AResident_Asset_C");
static_assert(offsetof(AResident_Asset_C, UberGraphFrame) == 0x000380, "Member 'AResident_Asset_C::UberGraphFrame' has a wrong offset!");

}

