#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Sense_List_Cell_01

#include "Basic.hpp"

#include "EndGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Sense_List_Cell_01.Sense_List_Cell_01_C
// 0x0008 (0x0368 - 0x0360)
class USense_List_Cell_01_C final : public UEndUserWidget
{
public:
	class UEndImage*                              Img_Base;                                          // 0x0360(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Sense_List_Cell_01_C">();
	}
	static class USense_List_Cell_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USense_List_Cell_01_C>();
	}
};
static_assert(alignof(USense_List_Cell_01_C) == 0x000008, "Wrong alignment on USense_List_Cell_01_C");
static_assert(sizeof(USense_List_Cell_01_C) == 0x000368, "Wrong size on USense_List_Cell_01_C");
static_assert(offsetof(USense_List_Cell_01_C, Img_Base) == 0x000360, "Member 'USense_List_Cell_01_C::Img_Base' has a wrong offset!");

}

