#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Startmenu_BtnLight_01

#include "Basic.hpp"


namespace SDK::Params
{

// Function Startmenu_BtnLight_01.Startmenu_BtnLight_01_C.ExecuteUbergraph_Startmenu_BtnLight_01
// 0x0008 (0x0008 - 0x0000)
struct Startmenu_BtnLight_01_C_ExecuteUbergraph_Startmenu_BtnLight_01 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_PlayAnimationByName_ReturnValue;          // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Startmenu_BtnLight_01_C_ExecuteUbergraph_Startmenu_BtnLight_01) == 0x000004, "Wrong alignment on Startmenu_BtnLight_01_C_ExecuteUbergraph_Startmenu_BtnLight_01");
static_assert(sizeof(Startmenu_BtnLight_01_C_ExecuteUbergraph_Startmenu_BtnLight_01) == 0x000008, "Wrong size on Startmenu_BtnLight_01_C_ExecuteUbergraph_Startmenu_BtnLight_01");
static_assert(offsetof(Startmenu_BtnLight_01_C_ExecuteUbergraph_Startmenu_BtnLight_01, EntryPoint) == 0x000000, "Member 'Startmenu_BtnLight_01_C_ExecuteUbergraph_Startmenu_BtnLight_01::EntryPoint' has a wrong offset!");
static_assert(offsetof(Startmenu_BtnLight_01_C_ExecuteUbergraph_Startmenu_BtnLight_01, CallFunc_PlayAnimationByName_ReturnValue) == 0x000004, "Member 'Startmenu_BtnLight_01_C_ExecuteUbergraph_Startmenu_BtnLight_01::CallFunc_PlayAnimationByName_ReturnValue' has a wrong offset!");

}

