#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VE0002_00_Helicopter_Standard_Animation

#include "Basic.hpp"


namespace SDK::Params
{

// Function VE0002_00_Helicopter_Standard_Animation.VE0002_00_Helicopter_Standard_Animation_C.ExecuteUbergraph_VE0002_00_Helicopter_Standard_Animation
// 0x0004 (0x0004 - 0x0000)
struct VE0002_00_Helicopter_Standard_Animation_C_ExecuteUbergraph_VE0002_00_Helicopter_Standard_Animation final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(VE0002_00_Helicopter_Standard_Animation_C_ExecuteUbergraph_VE0002_00_Helicopter_Standard_Animation) == 0x000004, "Wrong alignment on VE0002_00_Helicopter_Standard_Animation_C_ExecuteUbergraph_VE0002_00_Helicopter_Standard_Animation");
static_assert(sizeof(VE0002_00_Helicopter_Standard_Animation_C_ExecuteUbergraph_VE0002_00_Helicopter_Standard_Animation) == 0x000004, "Wrong size on VE0002_00_Helicopter_Standard_Animation_C_ExecuteUbergraph_VE0002_00_Helicopter_Standard_Animation");
static_assert(offsetof(VE0002_00_Helicopter_Standard_Animation_C_ExecuteUbergraph_VE0002_00_Helicopter_Standard_Animation, EntryPoint) == 0x000000, "Member 'VE0002_00_Helicopter_Standard_Animation_C_ExecuteUbergraph_VE0002_00_Helicopter_Standard_Animation::EntryPoint' has a wrong offset!");

}

