#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WE1006_00_Reno_Rod

#include "Basic.hpp"

#include "EndGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WE1006_00_Reno_Rod.WE1006_00_Reno_Rod_C
// 0x0010 (0x0EC8 - 0x0EB8)
class AWE1006_00_Reno_Rod_C final : public AEndSkeletalMeshActor
{
public:
	uint8                                         Pad_EB8[0x8];                                      // 0x0EB8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               FX_WE1006_00_ElcRod_01;                            // 0x0EC0(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WE1006_00_Reno_Rod_C">();
	}
	static class AWE1006_00_Reno_Rod_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWE1006_00_Reno_Rod_C>();
	}
};
static_assert(alignof(AWE1006_00_Reno_Rod_C) == 0x000008, "Wrong alignment on AWE1006_00_Reno_Rod_C");
static_assert(sizeof(AWE1006_00_Reno_Rod_C) == 0x000EC8, "Wrong size on AWE1006_00_Reno_Rod_C");
static_assert(offsetof(AWE1006_00_Reno_Rod_C, FX_WE1006_00_ElcRod_01) == 0x000EC0, "Member 'AWE1006_00_Reno_Rod_C::FX_WE1006_00_ElcRod_01' has a wrong offset!");

}

