#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WE1015_00_ThrowingItem_Standard

#include "Basic.hpp"

#include "WE1015_00_ThrowingItem_Standard_classes.hpp"


namespace SDK
{

// Function WE1015_00_ThrowingItem_Standard.WE1015_00_ThrowingItem_Standard_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AWE1015_00_ThrowingItem_Standard_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WE1015_00_ThrowingItem_Standard_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

