#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WE1012_00_RudeSunglassWpn_Standard

#include "Basic.hpp"

#include "EndGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WE1012_00_RudeSunglassWpn_Standard.WE1012_00_RudeSunglassWpn_Standard_C
// 0x0008 (0x0EC0 - 0x0EB8)
class AWE1012_00_RudeSunglassWpn_Standard_C final : public AEndSkeletalMeshActor
{
public:
	uint8                                         Pad_EB8[0x8];                                      // 0x0EB8(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WE1012_00_RudeSunglassWpn_Standard_C">();
	}
	static class AWE1012_00_RudeSunglassWpn_Standard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWE1012_00_RudeSunglassWpn_Standard_C>();
	}
};
static_assert(alignof(AWE1012_00_RudeSunglassWpn_Standard_C) == 0x000008, "Wrong alignment on AWE1012_00_RudeSunglassWpn_Standard_C");
static_assert(sizeof(AWE1012_00_RudeSunglassWpn_Standard_C) == 0x000EC0, "Wrong size on AWE1012_00_RudeSunglassWpn_Standard_C");

}

