#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WE1021_00_SephirothIllusion_Masamune

#include "Basic.hpp"

#include "EndGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WE1021_00_SephirothIllusion_Masamune.WE1021_00_SephirothIllusion_Masamune_C
// 0x0008 (0x0EC0 - 0x0EB8)
class AWE1021_00_SephirothIllusion_Masamune_C final : public AEndSkeletalMeshActor
{
public:
	uint8                                         Pad_EB8[0x8];                                      // 0x0EB8(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WE1021_00_SephirothIllusion_Masamune_C">();
	}
	static class AWE1021_00_SephirothIllusion_Masamune_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWE1021_00_SephirothIllusion_Masamune_C>();
	}
};
static_assert(alignof(AWE1021_00_SephirothIllusion_Masamune_C) == 0x000008, "Wrong alignment on AWE1021_00_SephirothIllusion_Masamune_C");
static_assert(sizeof(AWE1021_00_SephirothIllusion_Masamune_C) == 0x000EC0, "Wrong size on AWE1021_00_SephirothIllusion_Masamune_C");

}

