#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WE9007_00_MagnetGrenade_shell

#include "Basic.hpp"

#include "WE9007_00_MagnetGrenade_shell_classes.hpp"


namespace SDK
{

// Function WE9007_00_MagnetGrenade_shell.WE9007_00_MagnetGrenade_shell_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AWE9007_00_MagnetGrenade_shell_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WE9007_00_MagnetGrenade_shell_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

