#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Zero10_MAKO1_Layout_020_ClockTower

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass 010-MAKO1_Layout_020-ClockTower.010-MAKO1_Layout_020-ClockTower_C
// 0x0000 (0x0380 - 0x0380)
class AZero10_MAKO1_Layout_020_ClockTower_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"010-MAKO1_Layout_020-ClockTower_C">();
	}
	static class AZero10_MAKO1_Layout_020_ClockTower_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AZero10_MAKO1_Layout_020_ClockTower_C>();
	}
};
static_assert(alignof(AZero10_MAKO1_Layout_020_ClockTower_C) == 0x000008, "Wrong alignment on AZero10_MAKO1_Layout_020_ClockTower_C");
static_assert(sizeof(AZero10_MAKO1_Layout_020_ClockTower_C) == 0x000380, "Wrong size on AZero10_MAKO1_Layout_020_ClockTower_C");

}

