#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Zero10_MAKO1

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass 010-MAKO1.010-MAKO1_C
// 0x0008 (0x0388 - 0x0380)
class AZero10_MAKO1_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0380(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_010_MAKO1(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"010-MAKO1_C">();
	}
	static class AZero10_MAKO1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AZero10_MAKO1_C>();
	}
};
static_assert(alignof(AZero10_MAKO1_C) == 0x000008, "Wrong alignment on AZero10_MAKO1_C");
static_assert(sizeof(AZero10_MAKO1_C) == 0x000388, "Wrong size on AZero10_MAKO1_C");
static_assert(offsetof(AZero10_MAKO1_C, UberGraphFrame) == 0x000380, "Member 'AZero10_MAKO1_C::UberGraphFrame' has a wrong offset!");

}

